spring.application.name=npsv-gestor-tintas-backend

# ===============================
# Configuração do Admin Provisório
# ===============================
sistema.admin.email=admin@gestortintas.com
sistema.admin.senha=admin123


# ===============================
# Configuração do Banco (H2) TESTE
# ===============================
spring.datasource.url=jdbc:h2:mem:npsv_gestor_tintas_backend
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# -----------------------------------------------------------------------------------------------------

## --- Configuração do MySQL --- LOCAL
#
## A URL de Conexão JDBC
## jdbc:mysql://[host]:[porta]/[nome-do-banco-de-dados]
## (Usamos o banco 'meu_projeto' que você criou)
#spring.datasource.url=jdbc:mysql://localhost:3306/npsv_gestor_tintas_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#
## Usuário e Senha do Banco
#spring.datasource.username=root
#spring.datasource.password=senaisp
#
## O nome da classe do Driver (Boa prática, embora o Spring Boot geralmente infira)
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## --- Configurações do JPA/Hibernate (Opcional, mas recomendado) ---
#
## Define o "dialeto" do MySQL 8, para o Hibernate gerar o SQL correto
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## Mostra no console o SQL que o Hibernate está executando (ótimo para debug)
#spring.jpa.show-sql=true
#
## Gerenciamento automático do schema (tabelas)
## Opções comuns:
##   'none': Não faz nada (recomendado para produção)
##   'validate': Verifica se as tabelas e colunas batem com suas @Entities
##   'update': Atualiza o schema (cria tabelas/colunas) se faltar. (Bom para dev)
##   'create-drop': Cria tudo ao iniciar e destrói tudo ao fechar. (Bom para testes)
#spring.jpa.hibernate.ddl-auto=update

# -----------------------------------------------------------------------------------------------------



# ===============================
# Configuração JWT (exemplo)
# ===============================
# ${JWT_SECRET}
security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=600

# Configuração do broker (exemplo local)
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=app-local
mqtt.username=
mqtt.password=

# Configurações adicionais
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1

# Exemplo com SSL
# mqtt.broker-url=ssl://meu-broker:8883
# javax.net.ssl.trustStore=classpath:meu_truststore.jks
# javax.net.ssl.trustStorePassword=minhasenha
# javax.net.ssl.trustStoreType=JKS