spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

app.bootstrap.admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:}
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}