spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.bootstrap.admin.enabled=true
app.storage.public-base-url=http://10.0.2.2:8080

#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:db/dev-seed/seed_dev_data.sql
spring.jpa.defer-datasource-initialization=false

app.storage.provider=${APP_STORAGE_PROVIDER:local}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true